version: '3'
services:
  jenkins:
    container_name: jenkins
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
            #JENKINS_OPTS: "--httpPort=80"
      VIRTUAL_HOST: jenkin.haisannt.com
    ports:
      - 80:8080

volumes:
  jenkins-home: